package carpark;

import java.util.concurrent.atomic.AtomicInteger;

/**
 * Represents a single car that is generated by a {@link ProducerWorker},
 * placed into the {@link ParkingLot} buffer, and eventually retrieved by a
 * {@link ConsumerWorker}.
 *
 * <p>This class is intentionally immutable (all fields are {@code final})
 * because a {@code Car} instance is created once by a producer and never
 * modified afterwards, which keeps it inherently thread-safe with no need
 * for external synchronization.</p>
 */
public final class Car {

    /** Global counter used to generate unique, human-readable car IDs. */
    private static final AtomicInteger ID_GENERATOR = new AtomicInteger(1);

    private final int id;
    private final long creationTimeNanos;

    /**
     * Creates a new car and stamps it with the current time so that the
     * simulation can later measure how long it waited in the parking lot.
     */
    public Car() {
        this.id = ID_GENERATOR.getAndIncrement();
        this.creationTimeNanos = System.nanoTime();
    }

    /** @return the unique identifier of this car */
    public int getId() {
        return id;
    }

    /** @return the timestamp (nanoTime) at which this car was created */
    public long getCreationTimeNanos() {
        return creationTimeNanos;
    }

    @Override
    public String toString() {
        return "Car#" + id;
    }
}
